version: '2'
networks:
  dev-network:
    driver: bridge
services:
  dev-db:
    container_name: postgres
    image: postgres:16.3-alpine3.20
    restart: always
    env_file:
      - ./.env
    ports:
      - "5433:5432"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - dev-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - dev-network
